apiVersion: extensions/v1beta1
kind: Deployment                                          
metadata:
  name: todo-frontend
spec:
  replicas: 2                                             
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                  
    rollingUpdate: 
      maxUnavailable: 1                                   
      maxSurge: 1                                         
  template:
    metadata:
      labels:
        app: todo-frontend                                  
    spec:
      containers:
        - image: todo-frontend
          imagePullPolicy: IfNotPresent                        
          name: todo-frontend
          ports:
            - containerPort: 80